openapi: "3.0.0"
info:
  version: 1.0.8
  title: American Flights API
paths:
  /flights:
    get:
      operationId: getFlights
      parameters:
        - $ref: '#/components/parameters/client_id'
        - $ref: '#/components/parameters/client_secret'         
        - name: destination
          in: query
          schema:
            enum:
              - SFO
              - LAX
              - CLE
            type: string           
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                example:
                  - ID: 1
                    code: ER38sd
                    price: 400
                    departureDate: 2017/07/26
                    origin: CLE
                    destination: SFO
                    emptySeats: 0
                    plane:
                      type: Boeing 737
                      totalSeats: 150
                  - ID: 2
                    code: ER45if
                    price: 540.99
                    departureDate: 2017/07/27
                    origin: SFO
                    destination: ORD
                    emptySeats: 54
                    plane:
                      type: Boeing 777
                      totalSeats: 300
                type: array
                items:
                  $ref: '#/components/schemas/AmericanFlight'
    post:
      operationId: addFlight
      requestBody:
        content:
          application/json:
            example:
              code: GQ574
              price: 399
              departureDate: 2016/12/20
              origin: ORD
              destination: SFO
              emptySeats: 200
              plane:
                type: Boeing 747
                totalSeats: 400
            schema:
              $ref: '#/components/schemas/AmericanFlight'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                example:
                  message: Flight added (but not really)
  /flights/{ID}:
    get:
      operationId: getFlightByID
      parameters:
        - $ref: '#/components/parameters/client_id'
        - $ref: '#/components/parameters/client_secret'  
        - name: ID
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              example:
                ID: 1
                code: GQ574
                price: 399
                departureDate: 2016/12/20
                origin: ORD
                destination: SFO
                emptySeats: 200
                plane:
                  type: Boeing 747
                  totalSeats: 400
              schema:
                $ref: '#/components/schemas/AmericanFlight'

components:
  schemas:
    AmericanFlight:
      type: object
      properties:
        ID:
          type: integer
        code:
          type: string
        price:
          type: number
        departureDate:
          type: string
        origin:
          type: string
        destination:
          type: string
        emptySeats:
          type: integer
        plane:
          type: object
          properties:
            type:
              type: string
            totalSeats:
              type: integer
          required:
            - type
            - totalSeats
      required:
        - code
        - price
        - departureDate
        - origin
        - destination
        - emptySeats

  parameters:
    client_id:
      schema:
        type: string
      in: header
      name: client_id
      required: true
    client_secret:
      schema:
        type: string
      in: header
      name: client_secret
      required: true
  responses:
    trait_client-id-required_401:
      description: >
        Unauthorized, the client_id or client_secret are not valid
        or the client does not have access.
    trait_client-id-required_429:
      description: >
        The client used all of its request quota for the current period.
    trait_client-id-required_500:
      description: >
        An error occurred, see the specific message
        (Only if it is a WSDL endpoint).
    trait_client-id-required_503:
      description: Contracts Information Unreachable.
